2015-11-06 00:06:21 GMT LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
2015-11-06 00:07:48 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 00:07:48 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 00:08:10 GMT FATAL:  canceling authentication due to timeout
2015-11-06 00:08:55 GMT FATAL:  canceling authentication due to timeout
2015-11-06 01:19:47 GMT ERROR:  syntax error at or near "py_dump" at character 1
2015-11-06 01:19:47 GMT STATEMENT:  py_dump -U postgres -W -F t test1 > c:
	py_dump -U postgres -W -F t test1 > c:
	py_dump -U postgres -W -F t test1 > "c:\pgbackup\test1.tar"
	py_dump -U postgres -W -F t test1 > "c:\pgbackup\test1.tar";
2015-11-06 01:20:00 GMT ERROR:  syntax error at or near "py_dump" at character 1
2015-11-06 01:20:00 GMT STATEMENT:  py_dump -U postgres -W -F t test1 > "c:\pgbackup\test1.tar";
2015-11-06 01:21:36 GMT ERROR:  syntax error at or near "py_dump" at character 1
2015-11-06 01:21:36 GMT STATEMENT:  py_dump -U postgres -W -F t test1 > "c:\pgbackup\test1.tar"
	;
2015-11-06 01:25:39 GMT ERROR:  syntax error at or near "；" at character 1
2015-11-06 01:25:39 GMT STATEMENT:  ；
	py_dump -U postgres -W -F t test1 > "c:\backup\test1.tar";
2015-11-06 01:26:02 GMT ERROR:  syntax error at or near "py_dump" at character 1
2015-11-06 01:26:02 GMT STATEMENT:  py_dump -U postgres -W -F t test1 > "c:\backup\test1.tar" ;
2015-11-06 01:44:01 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 01:44:01 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:09:05 GMT ERROR:  database "test1" is being accessed by other users
2015-11-06 08:09:05 GMT DETAIL:  There are 2 other sessions using the database.
2015-11-06 08:09:05 GMT STATEMENT:  DROP DATABASE test1;
2015-11-06 08:09:23 GMT LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
2015-11-06 08:14:03 GMT ERROR:  relation "articles_article" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE articles_article (
	    id integer NOT NULL,
	    title text NOT NULL,
	    body text NOT NULL,
	    likes integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "articles_article_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE articles_article_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "articles_comment" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE articles_comment (
	    id integer NOT NULL,
	    text text NOT NULL,
	    article_id integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "articles_comment_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE articles_comment_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_group (
	    id integer NOT NULL,
	    name character varying(80) NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_group_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_group_permissions (
	    id integer NOT NULL,
	    group_id integer NOT NULL,
	    permission_id integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_permissions_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_group_permissions_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_permission" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_permission (
	    id integer NOT NULL,
	    name character varying(255) NOT NULL,
	    content_type_id integer NOT NULL,
	    codename character varying(100) NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_permission_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_permission_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_user (
	    id integer NOT NULL,
	    password character varying(128) NOT NULL,
	    last_login timestamp with time zone,
	    is_superuser boolean NOT NULL,
	    username character varying(30) NOT NULL,
	    first_name character varying(30) NOT NULL,
	    last_name character varying(30) NOT NULL,
	    email character varying(254) NOT NULL,
	    is_staff boolean NOT NULL,
	    is_active boolean NOT NULL,
	    date_joined timestamp with time zone NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_groups" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_user_groups (
	    id integer NOT NULL,
	    user_id integer NOT NULL,
	    group_id integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_groups_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_user_groups_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_user_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_user_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE auth_user_user_permissions (
	    id integer NOT NULL,
	    user_id integer NOT NULL,
	    permission_id integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_user_permissions_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE auth_user_user_permissions_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_admin_log" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE django_admin_log (
	    id integer NOT NULL,
	    action_time timestamp with time zone NOT NULL,
	    object_id text,
	    object_repr character varying(200) NOT NULL,
	    action_flag smallint NOT NULL,
	    change_message text NOT NULL,
	    content_type_id integer,
	    user_id integer NOT NULL,
	    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_admin_log_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE django_admin_log_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_content_type" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE django_content_type (
	    id integer NOT NULL,
	    app_label character varying(100) NOT NULL,
	    model character varying(100) NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_content_type_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE django_content_type_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_migrations" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE django_migrations (
	    id integer NOT NULL,
	    app character varying(255) NOT NULL,
	    name character varying(255) NOT NULL,
	    applied timestamp with time zone NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_migrations_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE django_migrations_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_session" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE django_session (
	    session_key character varying(40) NOT NULL,
	    session_data text NOT NULL,
	    expire_date timestamp with time zone NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "polls_choice" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE polls_choice (
	    id integer NOT NULL,
	    choice_text character varying(200) NOT NULL,
	    votes integer NOT NULL,
	    question_id integer NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "polls_choice_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE polls_choice_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "polls_question" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE TABLE polls_question (
	    id integer NOT NULL,
	    question_text character varying(200) NOT NULL,
	    pub_date timestamp with time zone NOT NULL
	);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "polls_question_id_seq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE SEQUENCE polls_question_id_seq
	    START WITH 1
	    INCREMENT BY 1
	    NO MINVALUE
	    NO MAXVALUE
	    CACHE 1;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  duplicate key value violates unique constraint "auth_permission_pkey"
2015-11-06 08:14:03 GMT DETAIL:  Key (id)=(1) already exists.
2015-11-06 08:14:03 GMT CONTEXT:  COPY auth_permission, line 1
2015-11-06 08:14:03 GMT STATEMENT:  COPY auth_permission (id, name, content_type_id, codename) FROM stdin;
	
2015-11-06 08:14:03 GMT ERROR:  duplicate key value violates unique constraint "django_content_type_pkey"
2015-11-06 08:14:03 GMT DETAIL:  Key (id)=(1) already exists.
2015-11-06 08:14:03 GMT CONTEXT:  COPY django_content_type, line 1
2015-11-06 08:14:03 GMT STATEMENT:  COPY django_content_type (id, app_label, model) FROM stdin;
	
2015-11-06 08:14:03 GMT ERROR:  duplicate key value violates unique constraint "django_migrations_pkey"
2015-11-06 08:14:03 GMT DETAIL:  Key (id)=(1) already exists.
2015-11-06 08:14:03 GMT CONTEXT:  COPY django_migrations, line 1
2015-11-06 08:14:03 GMT STATEMENT:  COPY django_migrations (id, app, name, applied) FROM stdin;
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "articles_article" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY articles_article
	    ADD CONSTRAINT articles_article_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "articles_comment" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY articles_comment
	    ADD CONSTRAINT articles_comment_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_name_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group
	    ADD CONSTRAINT auth_group_name_key UNIQUE (name);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_permissions_group_id_permission_id_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group_permissions
	    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_key UNIQUE (group_id, permission_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_group_permissions" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group_permissions
	    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_group" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group
	    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_permission_content_type_id_codename_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_permission
	    ADD CONSTRAINT auth_permission_content_type_id_codename_key UNIQUE (content_type_id, codename);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_permission" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_permission
	    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_user_groups" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_groups
	    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_groups_user_id_group_id_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_groups
	    ADD CONSTRAINT auth_user_groups_user_id_group_id_key UNIQUE (user_id, group_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_user" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user
	    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "auth_user_user_permissions" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_user_permissions
	    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_user_permissions_user_id_permission_id_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_user_permissions
	    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_key UNIQUE (user_id, permission_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_username_key" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user
	    ADD CONSTRAINT auth_user_username_key UNIQUE (username);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "django_admin_log" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_admin_log
	    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_content_type_app_label_2437cba1016f10ca_uniq" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_content_type
	    ADD CONSTRAINT django_content_type_app_label_2437cba1016f10ca_uniq UNIQUE (app_label, model);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "django_content_type" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_content_type
	    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "django_migrations" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_migrations
	    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "django_session" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_session
	    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "polls_choice" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY polls_choice
	    ADD CONSTRAINT polls_choice_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  multiple primary keys for table "polls_question" are not allowed
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY polls_question
	    ADD CONSTRAINT polls_question_pkey PRIMARY KEY (id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "articles_comment_a00c1b00" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX articles_comment_a00c1b00 ON articles_comment USING btree (article_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_name_662d5e40b0a7ce61_like" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_group_name_662d5e40b0a7ce61_like ON auth_group USING btree (name varchar_pattern_ops);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_permissions_0e939a4f" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_group_permissions_0e939a4f ON auth_group_permissions USING btree (group_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_group_permissions_8373b171" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_group_permissions_8373b171 ON auth_group_permissions USING btree (permission_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_permission_417f1b1c" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_permission_417f1b1c ON auth_permission USING btree (content_type_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_groups_0e939a4f" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_user_groups_0e939a4f ON auth_user_groups USING btree (group_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_groups_e8701ad4" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_user_groups_e8701ad4 ON auth_user_groups USING btree (user_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_user_permissions_8373b171" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_user_user_permissions_8373b171 ON auth_user_user_permissions USING btree (permission_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_user_permissions_e8701ad4" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_user_user_permissions_e8701ad4 ON auth_user_user_permissions USING btree (user_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "auth_user_username_3dbf168c9987ae06_like" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX auth_user_username_3dbf168c9987ae06_like ON auth_user USING btree (username varchar_pattern_ops);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_admin_log_417f1b1c" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX django_admin_log_417f1b1c ON django_admin_log USING btree (content_type_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_admin_log_e8701ad4" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX django_admin_log_e8701ad4 ON django_admin_log USING btree (user_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_session_de54fa62" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX django_session_de54fa62 ON django_session USING btree (expire_date);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "django_session_session_key_4eb4cbef0b2bc4f_like" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX django_session_session_key_4eb4cbef0b2bc4f_like ON django_session USING btree (session_key varchar_pattern_ops);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  relation "polls_choice_7aa0f6ee" already exists
2015-11-06 08:14:03 GMT STATEMENT:  CREATE INDEX polls_choice_7aa0f6ee ON polls_choice USING btree (question_id);
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "articles_com_article_id_723eaef4f4a43844_fk_articles_article_id" for relation "articles_comment" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY articles_comment
	    ADD CONSTRAINT articles_com_article_id_723eaef4f4a43844_fk_articles_article_id FOREIGN KEY (article_id) REFERENCES articles_article(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_content_type_id_2aeed125b429a0a0_fk_django_content_type_id" for relation "auth_permission" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_permission
	    ADD CONSTRAINT auth_content_type_id_2aeed125b429a0a0_fk_django_content_type_id FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_group_permissio_group_id_7300016467030660_fk_auth_group_id" for relation "auth_group_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group_permissions
	    ADD CONSTRAINT auth_group_permissio_group_id_7300016467030660_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_group_permission_id_7e455ca6aa837eb1_fk_auth_permission_id" for relation "auth_group_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_group_permissions
	    ADD CONSTRAINT auth_group_permission_id_7e455ca6aa837eb1_fk_auth_permission_id FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_user__permission_id_7f624618c54d317e_fk_auth_permission_id" for relation "auth_user_user_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_user_permissions
	    ADD CONSTRAINT auth_user__permission_id_7f624618c54d317e_fk_auth_permission_id FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_user_groups_group_id_48893fd701a5b624_fk_auth_group_id" for relation "auth_user_groups" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_groups
	    ADD CONSTRAINT auth_user_groups_group_id_48893fd701a5b624_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_user_groups_user_id_1934cb0f146e7796_fk_auth_user_id" for relation "auth_user_groups" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_groups
	    ADD CONSTRAINT auth_user_groups_user_id_1934cb0f146e7796_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "auth_user_user_permiss_user_id_18a73ddbee082213_fk_auth_user_id" for relation "auth_user_user_permissions" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY auth_user_user_permissions
	    ADD CONSTRAINT auth_user_user_permiss_user_id_18a73ddbee082213_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "djan_content_type_id_43bd8fffe5f6d56f_fk_django_content_type_id" for relation "django_admin_log" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_admin_log
	    ADD CONSTRAINT djan_content_type_id_43bd8fffe5f6d56f_fk_django_content_type_id FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "django_admin_log_user_id_2603725ab95e1215_fk_auth_user_id" for relation "django_admin_log" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY django_admin_log
	    ADD CONSTRAINT django_admin_log_user_id_2603725ab95e1215_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:14:03 GMT ERROR:  constraint "polls_choice_question_id_5878e07a68bd5fb3_fk_polls_question_id" for relation "polls_choice" already exists
2015-11-06 08:14:03 GMT STATEMENT:  ALTER TABLE ONLY polls_choice
	    ADD CONSTRAINT polls_choice_question_id_5878e07a68bd5fb3_fk_polls_question_id FOREIGN KEY (question_id) REFERENCES polls_question(id) DEFERRABLE INITIALLY DEFERRED;
	
	
	
2015-11-06 08:19:38 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:19:38 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:20:24 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:20:24 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:20:40 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:20:40 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:21:45 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:21:45 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:22:39 GMT FATAL:  canceling authentication due to timeout
2015-11-06 08:23:54 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:23:54 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:24:50 GMT FATAL:  canceling authentication due to timeout
2015-11-06 08:25:04 GMT ERROR:  syntax error at or near "py_dump" at character 1
2015-11-06 08:25:04 GMT STATEMENT:  py_dump -U postgres -W -F t test1 > "c:\pgbackup"test1.tar";
	;
	; py_dump -h localhost -F t test1 > "c:
	;
2015-11-06 08:30:23 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 08:30:23 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 08:31:19 GMT FATAL:  canceling authentication due to timeout
2015-11-06 10:02:43 GMT FATAL:  canceling authentication due to timeout
2015-11-06 10:02:54 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 10:02:54 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 10:03:10 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 10:03:10 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 10:03:21 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 10:03:21 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 10:04:07 GMT FATAL:  canceling authentication due to timeout
2015-11-06 10:04:17 GMT FATAL:  canceling authentication due to timeout
2015-11-06 14:12:46 GMT FATAL:  canceling authentication due to timeout
2015-11-06 14:13:40 GMT FATAL:  password authentication failed for user "yxy"
2015-11-06 14:13:40 GMT DETAIL:  Connection matched pg_hba.conf line 82: "host    all             all             ::1/128                 md5"
2015-11-06 14:14:11 GMT FATAL:  canceling authentication due to timeout
2015-11-06 14:14:22 GMT FATAL:  role "yxy" does not exist
2015-11-06 14:20:21 GMT FATAL:  role "yxy" does not exist
2015-11-06 14:29:47 GMT FATAL:  role "yxy" does not exist
